apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: monitoring # We put the monitor where Prometheus is
  labels:
    release: observability-stack # This label is CRITICAL for Prometheus to find it
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics # Matches ArgoCD metrics service
  namespaceSelector:
    matchNamespaces:
      - argocd
  endpoints:
  - port: metrics # The name of the port in the ArgoCD service
    path: /metrics
    interval: 15s
